baseurl = "https://rmdhnreza.my.id"
languageCode = "id-id"
theme = ["hugo-video", "hugo-theme-stack"]
paginate = 13
title = "rmdhnreza.my.id"
DefaultContentLanguage = "id"
ignoreErrors = "error-remote-getjson"
googleAnalytics = "UA-180998806-1" # Enable Google Analytics by entering your tracking id
enableRobotsTXT = true
canonifyURLs = true

[permalinks]
post = "/:title"

[params]
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true
# favicon = "favicon.ico"

  [params.footer]
  since = 2_020

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  # emoji = "🍥"
  subtitle = "Kumpulan Tutorial Untuk Linux & Windows"

  [params.article]
  math = false

    [params.article.license]
    enabled = false
    default = "Creative Commons Attribution 4.0 International"

  [params.comments]
  enabled = true
  provider = "disqus"

    [params.comments.utterances]
    issueTerm = "pathname"

    [params.comments.remark42]

  [params.widgets]
  enabled = [ "search", "archives", "categories" ] # "tag-cloud",

    [params.widgets.archives]
    limit = 5

    [params.widgets.tagCloud]
    limit = 10

    [params.widgets.categoriesCloud]
    limit = 20

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
pre = "home"

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "archives"
weight = -80
pre = "archives"

[[menu.main]]
identifier = "source"
name = "Source Code"
url = "https://github.com/rmdhnreza/rmdhnreza.my.id"
weight = -70
pre = "code-slash"

[[menu.main]]
identifier = "search"
name = "Search"
url = "search"
weight = -60
pre = "search"

[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 200

[markup.highlight]
noClasses = false

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      linkify = true

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = true
  appId = "Y9oQNP8KiGORnFYVlAYXMyz8-MdYXbMMI"
  appKey = "Nls4lGFA6b13yEb9ItK9wkzf"
  placeholder = "Berikan Komentar (Support Format Markdown)"
  visitor = true