baseurl: 'https://rmdhnreza.my.id'
languageCode: en-us
theme:
    - hugo-video
    - hugo-theme-stack
paginate: 13
title: rmdhnreza.my.id
DefaultContentLanguage: en
ignoreErrors: error-remote-getjson
googleAnalytics: UA-180998806-1
enableRobotsTXT: true
canonifyURLs: true

permalinks:
    post: '/:title'

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    footer:
        since: 2020
    dateFormat:
        published: 'Jan 02, 2006'
        lastUpdated: 'Jan 02, 2006 15:04 UTC'
    sidebar:
        subtitle: Blog Tutorial For Linux & Windows
    article:
        math: false
        toc: true
        license:
            enabled: false
            default: Creative Commons Attribution 4.0 International
    comments:
        enabled: true
        provider: disqus
        utterances:
            issueTerm: pathname
        remark42: {}
    widgets:
        enabled:
            - search
            - archives
            - categories
        archives:
            limit: 5
        tagCloud:
            limit: 10
        categoriesCloud:
            limit: 20
    opengraph:
        twitter:
            card: summary_large_image
    defaultImage:
        opengraph:
            enabled: false
            local: false
    colorScheme:
        toggle: true
        default: auto
    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true
    valine:
        enable: true
        appId: Y9oQNP8KiGORnFYVlAYXMyz8-MdYXbMMI
        appKey: Nls4lGFA6b13yEb9ItK9wkzf
        placeholder: Berikan Komentar (Support Format Markdown)
        visitor: true

menu:
    main:
        -
            identifier: home
            name: Home
            url: /
            weight: -100
            pre: home
        -
            identifier: archives
            name: Archives
            url: archives
            weight: -80
            pre: archives
        -
            identifier: source
            name: Source Code
            url: 'https://github.com/rmdhnreza/rmdhnreza.my.id'
            weight: -70
            pre: code-slash
        -
            identifier: search
            name: Search
            url: search
            weight: -60
            pre: search

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        -
            name: tags
            weight: 100
        -
            name: categories
            weight: 200

markup:
    defaultMarkdownHandler: goldmark
    goldmark:
        renderer:
            unsafe: true
        extensions:
            linkify: true
    highlight:
        noClasses: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2

build:
  writeStats: true