name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      git-ref:
        description:    
        required: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: Build
        run: hugo --gc --forceSyncStatic --minify --cleanDestinationDir

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RMDHNREZA }}'
          channelId: live
          projectId: rmdhnreza

      - name: Ping Sitemap URL
        uses: atymic/sitemap-ping-action@master
        with:
          sitemap-url: "https://rmdhnreza.my.id/sitemap.xml"

      - name: Ping Index URL
        uses: atymic/sitemap-ping-action@master
        with:      
          sitemap-url: "https://rmdhnreza.my.id/index.xml"